name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_RELEASE: Release
  BUILD_DEBUG: Debug

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_RELEASE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_RELEASE}}

  build-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_DEBUG}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_DEBUG}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_DEBUG}}

